<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="shape of a distribution, skewness, kurtosis, standard error of skewness, histogram, boxplot, JASP workflow">
<meta name="description" content="Chapter 2, part 1. Reading the shape of a distribution: peaks, symmetry, skewness and kurtosis with their standard errors, and a repeatable JASP workflow.">

<title>Part 1: The shape of a distribution – Decision Making for Management</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../weeks/week02-part2.html" rel="next">
<link href="../weeks/week01-independent-study.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3b4d8bd5646d865a73be5b7d80659dd7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Structured data for search and answer engines. The book is CC BY, so a
     model that cites it can say so. DefinedTermSet mirrors the Key terms
     section, whose entries carry the section ids these URLs point at. -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Book",
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/#book",
      "name": "Decision Making for Management",
      "alternateName": "A Student Textbook for Data-Informed Managerial Judgement",
      "inLanguage": "en-GB",
      "learningResourceType": "textbook",
      "educationalLevel": "undergraduate",
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "author": {
        "@type": "Person",
        "name": "Mohammed Ali Sharafuddin",
        "affiliation": {
          "@type": "CollegeOrUniversity",
          "name": "Qasim Ibrahim School of Business, Villa College"
        }
      },
      "educationalUse": ["instruction", "self study"],
      "audience": {
        "@type": "EducationalAudience",
        "educationalRole": "student"
      },
      "usageInfo": "https://mohammedalisharafuddin.github.io/dmm-textbook/front-matter/ai-use.html",
      "about": [
        "Business statistics",
        "Descriptive statistics",
        "Data-informed decision making"
      ]
    },
    {
      "@type": ["Chapter", "LearningResource"],
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#chapter",
      "name": "Data, Measurement Scales, and Descriptive Statistics",
      "position": 1,
      "isPartOf": { "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/#book" },
      "inLanguage": "en-GB",
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "educationalLevel": "undergraduate",
      "learningResourceType": "chapter",
      "timeRequired": "PT9H",
      "educationalUse": ["instruction", "self study"],
      "assessmentType": ["formative exit check", "checkpoint quiz", "tutorial upload"],
      "usageInfo": "https://mohammedalisharafuddin.github.io/dmm-textbook/front-matter/ai-use.html",
      "educationalAlignment": {
        "@type": "AlignmentObject",
        "alignmentType": "teaches",
        "targetName": "Descriptive statistics for management decisions"
      },
      "teaches": [
        "Explain why a manager describes evidence before acting on it",
        "Distinguish a case, a variable, an observation and a value in a real dataset",
        "Separate a population from a sample, and a parameter from a statistic",
        "Say what descriptive statistics can establish and what only inference can",
        "Classify a variable as nominal, ordinal, interval or ratio, and as discrete or continuous",
        "Identify which variable is independent and which is dependent in a stated question",
        "Build and read frequency, relative frequency, grouped and cumulative frequency tables",
        "Choose a graph that suits the variable type and the question",
        "Calculate and interpret the mean, median, mode, range, variance, standard deviation, quartiles and the interquartile range",
        "Recognise a misleading summary or display and say why it misleads"
      ]
    },
    {
      "@type": "DefinedTermSet",
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#key-terms",
      "name": "Key terms, Chapter 1",
      "hasDefinedTerm": [
        { "@type": "DefinedTerm", "name": "Case", "description": "The unit the data describe.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-cases" },
        { "@type": "DefinedTerm", "name": "Variable", "description": "A characteristic measured on each case.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-cases" },
        { "@type": "DefinedTerm", "name": "Population", "description": "Every case of interest.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Sample", "description": "The subset of the population actually measured.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Parameter", "description": "A number describing a population.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Statistic", "description": "A number describing a sample.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Nominal", "description": "Named categories with no order. You may count them, find the mode and take proportions.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Ordinal", "description": "Ordered categories where the size of the gaps between them is unknown.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Interval", "description": "Numeric with equal gaps and a zero placed by convention, so ratios have no meaning.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Ratio", "description": "Numeric with equal gaps and a true zero, so ratios are meaningful.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Mean", "description": "The sum of all values divided by how many there are.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-centre" },
        { "@type": "DefinedTerm", "name": "Median", "description": "The middle value once the data are in order.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-centre" },
        { "@type": "DefinedTerm", "name": "Mode", "description": "The value that occurs most often, read off a frequency table.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-centre" },
        { "@type": "DefinedTerm", "name": "Standard deviation", "description": "The square root of the variance, in the original units of the data.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-spread" },
        { "@type": "DefinedTerm", "name": "Interquartile range", "description": "The third quartile minus the first, the spread of the middle half.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-quartiles" },
        { "@type": "DefinedTerm", "name": "Outlier", "description": "A value beyond 1.5 times the interquartile range from the nearer quartile.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-shape" }
      ]
    },
    {
      "@type": ["Chapter", "LearningResource"],
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#chapter",
      "name": "Introduction to JASP and the Normal Distribution",
      "position": 2,
      "isPartOf": { "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/#book" },
      "inLanguage": "en-GB",
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "educationalLevel": "undergraduate",
      "learningResourceType": "chapter",
      "timeRequired": "PT9H",
      "educationalUse": ["instruction", "self study"],
      "assessmentType": ["formative exit check", "checkpoint quiz", "tutorial upload"],
      "usageInfo": "https://mohammedalisharafuddin.github.io/dmm-textbook/front-matter/ai-use.html",
      "educationalAlignment": {
        "@type": "AlignmentObject",
        "alignmentType": "teaches",
        "targetName": "The normal distribution and z-scores for management decisions"
      },
      "teaches": [
        "Describe the shape of a distribution from a histogram and a boxplot, naming its peaks, its symmetry and its tails",
        "Interpret skewness and kurtosis, and judge each against its standard error",
        "Follow a repeatable workflow in JASP or PocketStat from loading a file to an annotated output",
        "State the properties of the normal distribution and use the empirical rule to estimate the share of cases within one, two and three standard deviations of the mean",
        "Apply Chebyshev's rule when the shape of a distribution is unknown or clearly non-normal",
        "Calculate a z-score, convert a z-score back into the original units, and use z-scores to compare values measured in different units",
        "Classify a value as typical, unusual or extreme from its z-score, and explain in plain language what that means for a manager",
        "Use the standard normal table to find the share of cases above, below or between two values, and the value that marks a given percentile",
        "Judge whether a variable is close enough to normal for the normal model, using a histogram, a Q-Q plot, skewness, kurtosis and the Shapiro-Wilk test",
        "Recognise when the normal model gives impossible or distorted answers, and report the alternative"
      ]
    },
    {
      "@type": "DefinedTermSet",
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#key-terms",
      "name": "Key terms, Chapter 2",
      "hasDefinedTerm": [
        { "@type": "DefinedTerm", "name": "Distribution", "description": "The values a variable takes, and how often each occurs.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-position" },
        { "@type": "DefinedTerm", "name": "Ceiling effect", "description": "Cases piled up at the highest value a scale allows, which cuts off the right tail.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-shape-reading" },
        { "@type": "DefinedTerm", "name": "Skewness", "description": "How far a distribution leans to one side. Positive for a longer right tail, negative for a longer left tail.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-skewness" },
        { "@type": "DefinedTerm", "name": "Standard error", "description": "How much a statistic would typically vary from one sample to the next.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-skewness" },
        { "@type": "DefinedTerm", "name": "Kurtosis", "description": "How heavy the tails of a distribution are compared with a normal distribution, reported as excess kurtosis with 0 for normal.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-kurtosis" },
        { "@type": "DefinedTerm", "name": "Normal distribution", "description": "A symmetric bell-shaped model fixed by its mean and standard deviation, whose areas are shares of cases.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-normal" },
        { "@type": "DefinedTerm", "name": "Empirical rule", "description": "In a normal distribution about 68, 95 and 99.7 per cent of cases lie within one, two and three standard deviations of the mean.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-empirical" },
        { "@type": "DefinedTerm", "name": "Chebyshev's rule", "description": "For any distribution, at least 1 minus 1 over k squared of the cases lie within k standard deviations of the mean.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-chebyshev" },
        { "@type": "DefinedTerm", "name": "z-score", "description": "How many standard deviations a value lies above or below the mean.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-zscores" },
        { "@type": "DefinedTerm", "name": "Standard normal distribution", "description": "The normal distribution with a mean of 0 and a standard deviation of 1.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part3.html#sec-standard-normal" },
        { "@type": "DefinedTerm", "name": "Q-Q plot", "description": "A plot of sorted data against the values a normal distribution predicts for each position. Normal data lie on a straight line.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part3.html#sec-normality" },
        { "@type": "DefinedTerm", "name": "Shapiro-Wilk test", "description": "A test of how closely data follow the pattern a normal distribution would produce. Its verdict depends heavily on sample size.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part3.html#sec-normality" }
      ]
    }
  ]
}
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/fonts.css">
<link rel="stylesheet" href="../assets/css/typography.css">
<link rel="stylesheet" href="../assets/css/student-book.css">
<meta property="og:title" content="Part 1: The shape of a distribution – Decision Making for Management">
<meta property="og:description" content="A CC BY undergraduate textbook that teaches descriptive and inferential statistics through management decisions, using JASP and PocketStat.">
<meta property="og:image" content="https://mohammedalisharafuddin.github.io/dmm-textbook/assets/images/screenshots/ch02/ch02-jasp-f1-four-distribution-plots.png">
<meta property="og:site_name" content="Decision Making for Management">
<meta property="og:locale" content="en_GB">
<meta property="og:image:alt" content="Four JASP distribution plots in a two-by-two grid. Waiting_Time_Mins rises to a single peak in the mid-40s with roughly equal tails. Spending has a tall peak between 500 and 600 USD, an empty gap between 700 and 800, and a smaller second peak near 1,000. Satisfaction peaks near 4 and is cut off sharply at 5 on the right. Age is broad and flat between 25 and 45 with no single tall peak.">
<meta property="og:image:height" content="743">
<meta property="og:image:width" content="1015">
<meta name="twitter:title" content="Part 1: The shape of a distribution – Decision Making for Management">
<meta name="twitter:description" content="A CC BY undergraduate textbook that teaches descriptive and inferential statistics through management decisions, using JASP and PocketStat.">
<meta name="twitter:image" content="https://mohammedalisharafuddin.github.io/dmm-textbook/assets/images/screenshots/ch02/ch02-jasp-f1-four-distribution-plots.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="Four JASP distribution plots in a two-by-two grid. Waiting_Time_Mins rises to a single peak in the mid-40s with roughly equal tails. Spending has a tall peak between 500 and 600 USD, an empty gap between 700 and 800, and a smaller second peak near 1,000. Satisfaction peaks near 4 and is cut off sharply at 5 on the right. Age is broad and flat between 25 and 45 with no single tall peak.">
<meta name="twitter:image-height" content="743">
<meta name="twitter:image-width" content="1015">
<meta name="dmm-crossref-renumbered" content="1"></head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../weeks/week02.html">Chapter 2: Introduction to JASP and the Normal Distribution</a></li><li class="breadcrumb-item"><a href="../weeks/week02.html"><span class="chapter-title">Part 1: The shape of a distribution</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Decision Making for Management</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decision Making for Management</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/copyright.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Copyright and Attribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/ai-use.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using AI on This Module</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/how-to-use-this-book.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use This Book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/software-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software Guide</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/dataset-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dataset Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Chapter 1: Data, Measurement Scales, and Descriptive Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 1: Foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-part2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 2: Variables and displays</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-part3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 3: Centre and spread</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-reference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Running the analysis, and chapter reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial: First descriptive statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-independent-study.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Independent study</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Chapter 2: Introduction to JASP and the Normal Distribution</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Part 1: The shape of a distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-part2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 2: The normal curve and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-part3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 3: Areas, percentiles and checking normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-reference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Running the analysis, and chapter reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial: JASP setup, normality, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-independent-study.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Independent study</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#this-chapters-lecture" id="toc-this-chapters-lecture" class="nav-link active" data-scroll-target="#this-chapters-lecture">This chapter’s lecture</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#sec-position" id="toc-sec-position" class="nav-link" data-scroll-target="#sec-position">Where a value sits</a>
  <ul class="collapse">
  <li><a href="#four-terms-for-this-chapter" id="toc-four-terms-for-this-chapter" class="nav-link" data-scroll-target="#four-terms-for-this-chapter">Four terms for this chapter</a></li>
  </ul></li>
  <li><a href="#sec-shape-reading" id="toc-sec-shape-reading" class="nav-link" data-scroll-target="#sec-shape-reading">Reading a histogram for shape</a></li>
  <li><a href="#sec-skewness" id="toc-sec-skewness" class="nav-link" data-scroll-target="#sec-skewness">Skewness as a number</a>
  <ul class="collapse">
  <li><a href="#skewness-against-its-standard-error" id="toc-skewness-against-its-standard-error" class="nav-link" data-scroll-target="#skewness-against-its-standard-error">Skewness against its standard error</a></li>
  </ul></li>
  <li><a href="#sec-kurtosis" id="toc-sec-kurtosis" class="nav-link" data-scroll-target="#sec-kurtosis">Kurtosis and the tails</a></li>
  <li><a href="#sec-boxplot-shape" id="toc-sec-boxplot-shape" class="nav-link" data-scroll-target="#sec-boxplot-shape">Boxplots and shape</a></li>
  <li><a href="#sec-workflow" id="toc-sec-workflow" class="nav-link" data-scroll-target="#sec-workflow">A repeatable workflow</a></li>
  <li><a href="#section-summary" id="toc-section-summary" class="nav-link" data-scroll-target="#section-summary">Section summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../weeks/week02.html">Chapter 2: Introduction to JASP and the Normal Distribution</a></li><li class="breadcrumb-item"><a href="../weeks/week02.html"><span class="chapter-title">Part 1: The shape of a distribution</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Part 1: The shape of a distribution</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>shape of a distribution, skewness, kurtosis, standard error of skewness, histogram, boxplot, JASP workflow</p>
  </div>
</div>

</header>


<div class="callout callout-style-default callout-note callout-titled" title="The decision question for this chapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The decision question for this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p>The same service manager from chapter 1 has read your summary and comes back with two sharper questions. <strong>One customer waited 77 minutes. Was that an ordinary bad day, or a sign that something went wrong? And can the branch promise that nine customers in ten will be seen within an hour?</strong></p>
<p>Chapter 1 gave you the centre and the spread of the waiting times. To answer these questions you need to know where a single value falls inside the distribution, and what share of customers falls beyond a given point. That takes the shape of the distribution, the normal curve, and the z-score.</p>
<p>You will use the same file, <code>DMM_Teaching_Data_Full.csv</code>, 200 customer records with 26 variables. Every figure quoted in this chapter comes from that file and is printed on the page. The <a href="../front-matter/dataset-overview.html">dataset overview</a> lists every variable it contains.</p>
</div>
</div>
<section id="this-chapters-lecture" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="this-chapters-lecture">This chapter’s lecture</h2>
<div class="lp-header lecture">
<p><span class="lp-type">Lecture</span> <strong>JASP workflow and normal distribution</strong> <span class="lp-meta">1 hour · 4 activities</span></p>
</div>
<div class="lp-grid lp-4">
<div class="lp-card lecture">
<p><span class="badge bg-discussion">Discussion</span></p>
<p><strong><span class="act-num">1</span> Welcome and weekly goals</strong></p>
<p><span class="act-time">⏱ 10 min</span></p>
<p>Connect last week’s descriptive work to the shape, the spread and the unusual values in a dataset.</p>
</div>
<div class="lp-card lecture">
<p><span class="badge bg-acquisition">Acquisition</span></p>
<p><strong><span class="act-num">2</span> Normal curve and z-scores</strong></p>
<p><span class="act-time">⏱ 30 min</span></p>
<p>How the normal distribution, the empirical rule and z-scores help you judge whether a value is typical or unusual.</p>
</div>
<div class="lp-card lecture">
<p><span class="badge bg-practice">Practice</span></p>
<p><strong><span class="act-num">3</span> Worked example and discussion</strong></p>
<p><span class="act-time">⏱ 15 min</span></p>
<p>Work through a short example and explain what a z-score tells you in plain language.</p>
</div>
<div class="lp-card lecture">
<p><span class="badge bg-assessment">Assessment</span></p>
<p><strong><span class="act-num">4</span> Exit check</strong></p>
<p><span class="act-time">⏱ 5 min</span></p>
<p>A short exit check on the normal curve or z-score interpretation.</p>
</div>
</div>
</section>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>After studying this chapter you should be able to:</p>
<ol type="1">
<li>Describe the shape of a distribution from a histogram and a boxplot, naming its peaks, its symmetry and its tails.</li>
<li>Interpret skewness and kurtosis, and judge each against its standard error.</li>
<li>Follow a repeatable workflow in JASP or PocketStat from loading a file to an annotated output.</li>
<li>State the properties of the normal distribution and use the empirical rule to estimate the share of cases within one, two and three standard deviations of the mean.</li>
<li>Apply Chebyshev’s rule when the shape of a distribution is unknown or clearly non-normal.</li>
<li>Calculate a z-score, convert a z-score back into the original units, and use z-scores to compare values measured in different units.</li>
<li>Classify a value as typical, unusual or extreme from its z-score, and explain in plain language what that means for a manager.</li>
<li>Use the standard normal table to find the share of cases above, below or between two values, and the value that marks a given percentile.</li>
<li>Judge whether a variable is close enough to normal for the normal model, using a histogram, a Q-Q plot, skewness, kurtosis and the Shapiro-Wilk test.</li>
<li>Recognise when the normal model gives impossible or distorted answers, and report the alternative.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="How to use this chapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How to use this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p>This week’s learning plan is 9 hours: 1 hour of synchronous lecture, 2 hours of synchronous tutorial, and 6 hours of asynchronous self-study.</p>
<p>You must read all four parts of this chapter in full before moving to the tutorial. You are permitted to use Google NotebookLM to brainstorm the concepts. Complete the worked examples and the Try It exercises yourself, with no AI assistance. The full policy, and the reason NotebookLM is the only tool permitted, is on the <a href="../front-matter/ai-use.html">Using AI on This Module</a> page. NotebookLM reads one web page per source, so add all six pages of this chapter to your notebook, as set out in <a href="../front-matter/ai-use.html#sec-notebooklm">adding a chapter to NotebookLM</a>.</p>
<p>Keep a calculator beside you. Every z-score in this chapter is worked by hand once, and the tutorial asks you to check the software against your own arithmetic.</p>
<p>If you finish this chapter before the planned time, continue to the recommended reading in the independent study section. Use the independent study for revision, then take the checkpoint quiz.</p>
</div>
</div>
</section>
<section id="sec-position" class="level2">
<h2 class="anchored" data-anchor-id="sec-position">Where a value sits</h2>
<p>A single value means little until you know where it sits among the others. Chapter 1 gave you two numbers for the waiting times in the teaching dataset: a mean of 45.5 minutes and a standard deviation of 11.9 minutes. Those two numbers describe the column as a whole. The manager’s question is about one customer.</p>
<p>For example: respondent 58 waited 77 minutes. That is 31.5 minutes above the mean. Whether 31.5 minutes is a lot depends on how much waiting times usually vary. In a branch where almost every wait falls between 44 and 47 minutes, 77 would be astonishing. In a branch where waits range freely from 10 minutes to two hours, 77 would pass unnoticed.</p>
<p>The position of a value depends on two factors. The first is its distance from the centre and the second is the spread that distance is measured against. The <strong>shape</strong> of the distribution acts as a third factor that determines how to read the result. Distance and spread tell you how far out a value falls. Shape tells you how many other cases you should expect to find that far out.</p>
<section id="four-terms-for-this-chapter" class="level3">
<h3 class="anchored" data-anchor-id="four-terms-for-this-chapter">Four terms for this chapter</h3>
<p>Four terms appear throughout the chapter. Each gets a full section later. You need to recognise all four now, because the next few pages use them before those sections arrive.</p>
<p>A <strong>distribution</strong> is the pattern of values a variable takes: which values occur, and how often. A frequency table and a histogram are two ways of displaying one.</p>
<p>The <strong>shape</strong> of a distribution is the outline its histogram makes: where it peaks, whether its two sides mirror each other, and how far its tails stretch.</p>
<p>The <strong>normal distribution</strong> is a particular symmetric, bell-shaped curve. It serves as a reference model, and much of statistics compares real data against it.</p>
<p>A <strong>z-score</strong> states how many standard deviations a value lies above or below the mean. Respondent 58’s wait of 77 minutes has a z-score of 2.65, meaning it lies 2.65 standard deviations above the mean. <a href="week02-part2.html#sec-zscores" class="quarto-xref"><span>z-scores</span></a> shows how that number is calculated and what it tells a manager.</p>
</section>
</section>
<section id="sec-shape-reading" class="level2">
<h2 class="anchored" data-anchor-id="sec-shape-reading">Reading a histogram for shape</h2>
<p>A histogram shows the shape of a continuous variable directly. You met it in chapter 1 as the display for one measurement across all cases. This chapter reads it more closely, and asks three questions of every histogram you draw.</p>
<p><strong>How many peaks?</strong> A distribution with one clear peak is <strong>unimodal</strong>. A distribution with two separate peaks is bimodal in shape, which usually means two different groups share one column. Chapter 1 used “bimodal” for a column with two equally frequent values. Waiting time had two, 42 and 47 minutes, each recorded 10 times. Its histogram still rises to a single peak in the mid-40s, so its shape is unimodal. In this chapter, unimodal and bimodal describe the shape of the histogram.</p>
<p><strong>Do the two sides mirror each other?</strong> A distribution whose left and right halves are close to mirror images is <strong>symmetric</strong>. One with a longer tail on one side is <strong>skewed</strong> towards that side. Chapter 1 showed you how to spot skew by comparing the mean with the median. This chapter adds a number that measures it.</p>
<p><strong>How heavy are the tails?</strong> Two distributions can share a centre, a spread and perfect symmetry, and still differ in how often extreme values occur. One piles its cases tightly around the centre and sends a few far out. The other spreads its cases evenly across the range and has almost none in the far tails. Kurtosis measures this property, and <a href="#sec-kurtosis" class="quarto-xref"><span>Kurtosis and the tails</span></a> covers it.</p>
<div id="fig-four-shapes" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four JASP distribution plots in a two-by-two grid. Waiting_Time_Mins rises to a single peak in the mid-40s with roughly equal tails. Spending has a tall peak between 500 and 600 USD, an empty gap between 700 and 800, and a smaller second peak near 1,000. Satisfaction peaks near 4 and is cut off sharply at 5 on the right. Age is broad and flat between 25 and 45 with no single tall peak.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-four-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/screenshots/ch02/ch02-jasp-f1-four-distribution-plots.png" class="img-fluid figure-img" alt="Four JASP distribution plots in a two-by-two grid. Waiting_Time_Mins rises to a single peak in the mid-40s with roughly equal tails. Spending has a tall peak between 500 and 600 USD, an empty gap between 700 and 800, and a smaller second peak near 1,000. Satisfaction peaks near 4 and is cut off sharply at 5 on the right. Age is broad and flat between 25 and 45 with no single tall peak.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-four-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Distribution plots for four variables in the teaching dataset, as JASP draws them.
</figcaption>
</figure>
</div>
<p>The four variables in <a href="#fig-four-shapes" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> show four different shapes, and each one shows a different pattern to a manager.</p>
<div id="tbl-four-shapes" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-four-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Centre, range and shape for four variables in the teaching dataset
</figcaption>
<div aria-describedby="tbl-four-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Mean</th>
<th>Median</th>
<th>Minimum</th>
<th>Maximum</th>
<th>Shape</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Waiting_Time_Mins</code></td>
<td>45.46</td>
<td>46.00</td>
<td>12</td>
<td>90</td>
<td>One peak, close to symmetric</td>
</tr>
<tr class="even">
<td><code>Spending</code></td>
<td>505.65</td>
<td>494.28</td>
<td>6.34</td>
<td>1,201.01</td>
<td>Two peaks: most near 500, a VIP group near 1,000</td>
</tr>
<tr class="odd">
<td><code>Satisfaction</code></td>
<td>3.81</td>
<td>3.86</td>
<td>1.58</td>
<td>5.00</td>
<td>One peak, cut off at the top of the scale</td>
</tr>
<tr class="even">
<td><code>Age</code></td>
<td>35.35</td>
<td>35.00</td>
<td>22</td>
<td>52</td>
<td>Symmetric, broad and flat</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><code>Satisfaction</code> needs a closer look. The score runs from 1 to 5, and 12 of the 200 customers scored exactly 5.00, the highest score the scale allows. A scale with a maximum stops the right tail at that maximum. Any customer who would have scored above 5 is recorded as 5, so the cases pile up against the top of the scale. This pile-up is called a <strong>ceiling effect</strong>, and the longer tail appears on the left. A floor effect is the same pattern at the bottom of a scale.</p>
<div class="worked-example">
<p><span class="we-label">Worked example 2.1</span></p>
<section id="describing-a-shape-in-words" class="level3">
<h3 class="anchored" data-anchor-id="describing-a-shape-in-words">Describing a shape in words</h3>
<div class="we-problem">
<p>The histogram of <code>Spending</code> in <a href="#fig-four-shapes" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> rises to a tall peak between 500 and 600 USD, drops to nothing between 700 and 800 USD, and rises again to a smaller peak near 1,000 USD. The lowest value is 6.34 USD and the highest is 1,201.01. The mean is 505.65 and the median is 494.28.</p>
<p>Describe the shape in one sentence a manager could read, name the evidence for each part of the description, and suggest what the second peak might be.</p>
</div>
<div class="we-solution">
<p><strong>Description:</strong> Spending has two peaks: most customers spend up to about 700 USD, centred near 500, and a separate group of 30 customers spends between 850 and 1,200 USD.</p>
<p><strong>Evidence, part by part:</strong></p>
<ul>
<li><em>Two peaks.</em> The tallest bar, 500 to 600 USD, holds 47 customers. A second, smaller rise peaks at 900 to 1,000 USD, with 13 customers.</li>
<li><em>A gap between them.</em> No customer spent between 700 and 800 USD, so the two groups do not overlap.</li>
<li><em>A lean to the right.</em> The mean is 11.37 USD above the median. The high group pulls the mean up. The median stays near the middle of the main group.</li>
</ul>
<p><strong>What the second peak is:</strong> Two peaks usually mean two groups share one column. <code>Ticket_Type</code> confirms it. The 30 customers above 800 USD are exactly the 30 VIP ticket holders, and no standard or student customer spent more than 700 USD.</p>
<p>A manager reading the sentence learns that VIP customers are a distinct group. They are 15 per cent of customers and bring in 29 per cent of all spending, so their spending belongs in its own line of the report.</p>
</div>
</section>
</div>
</section>
<section id="sec-skewness" class="level2">
<h2 class="anchored" data-anchor-id="sec-skewness">Skewness as a number</h2>
<p><strong>Skewness</strong> measures how far a distribution leans to one side. JASP and PocketStat both report it as a single number.</p>
<ul>
<li>A skewness near <strong>0</strong> means the distribution is close to symmetric.</li>
<li>A <strong>positive</strong> skewness means a longer tail on the right, called right skew or positive skew.</li>
<li>A <strong>negative</strong> skewness means a longer tail on the left, called left skew or negative skew.</li>
</ul>
<p>The sign gives the direction. The size gives the strength of the lean. A common rule of thumb for the size reads as follows.</p>
<div id="tbl-skew-size" class="tbl-grid quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-skew-size-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: A rule of thumb for the size of skewness
</figcaption>
<div aria-describedby="tbl-skew-size-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-grid caption-top table">
<thead>
<tr class="header">
<th>Skewness, ignoring the sign</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Under 0.5</td>
<td>Close to symmetric</td>
</tr>
<tr class="even">
<td>0.5 to 1</td>
<td>Moderately skewed</td>
</tr>
<tr class="odd">
<td>Over 1</td>
<td>Strongly skewed</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The statistic is built from cubed z-scores: each value’s distance from the mean in standard deviations, cubed, then averaged. Cubing keeps the sign, so values far above the mean push the total up and values far below push it down. Cubing also magnifies the far values, so the tails dominate the result. You will read skewness from the software, and the formula appears in the formula review on the <a href="week02-reference.html#sec-formulae">reference page</a> for anyone who wants it.</p>
<section id="skewness-against-its-standard-error" class="level3">
<h3 class="anchored" data-anchor-id="skewness-against-its-standard-error">Skewness against its standard error</h3>
<p>Every statistic calculated from a sample would come out a little different in another sample. The <strong>standard error</strong> of a statistic measures how much it would typically vary from one sample to the next. Chapter 4 builds on the standard error in detail. Here you need it for one purpose: to judge whether a skewness figure is larger than sampling variation alone would produce.</p>
<p>JASP reports the standard error of skewness beside the skewness itself. For a sample of 200, the standard error is 0.172. Divide the skewness by its standard error:</p>
<p><span class="math display">\[\text{skewness ratio} = \frac{\text{skewness}}{\text{SE of skewness}}\]</span></p>
<p>A ratio beyond 2 in either direction indicates skew that is more than sampling variation. A ratio between <span class="math inline">\(-2\)</span> and <span class="math inline">\(+2\)</span> is consistent with a symmetric population.</p>
<div id="tbl-skewness" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-skewness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: Skewness as JASP reports it for four variables in the teaching dataset
</figcaption>
<div aria-describedby="tbl-skewness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Skewness</th>
<th>SE</th>
<th>Ratio</th>
<th>Size</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Waiting_Time_Mins</code></td>
<td>0.112</td>
<td>0.172</td>
<td>0.65</td>
<td>Under 0.5</td>
<td>Symmetric</td>
</tr>
<tr class="even">
<td><code>Age</code></td>
<td>0.038</td>
<td>0.172</td>
<td>0.22</td>
<td>Under 0.5</td>
<td>Symmetric</td>
</tr>
<tr class="odd">
<td><code>Satisfaction</code></td>
<td>-0.289</td>
<td>0.172</td>
<td>-1.68</td>
<td>Under 0.5</td>
<td>Mild left lean, within sampling variation</td>
</tr>
<tr class="even">
<td><code>Spending</code></td>
<td>0.635</td>
<td>0.172</td>
<td>3.69</td>
<td>0.5 to 1</td>
<td>Moderately right-skewed</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-skewness" class="quarto-xref">Table&nbsp;<span>2.3</span></a> rounds every figure to three decimal places. JASP’s default display shows four significant figures, so your own output reads 0.1116 for waiting time, 0.03785 for age and 0.1719 for the standard error. The values are the same. To make JASP print three decimal places, open <strong>Preferences</strong>, choose <strong>Results</strong>, and set <strong>Fix the number of decimals</strong> to 3, as the tutorial does in its second step.</p>
<p>The two rules answer different questions. The size rule asks whether the lean is large enough to matter for the summary you choose. The ratio asks whether the lean is larger than chance. With a large sample, the ratio flags small leans that make no practical difference. With a small sample, it misses large ones. Read both, and let the histogram settle any disagreement.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Why JASP and PocketStat give slightly different skewness">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why JASP and PocketStat give slightly different skewness
</div>
</div>
<div class="callout-body-container callout-body">
<p>JASP reports a skewness of 0.112 for <code>Waiting_Time_Mins</code>. PocketStat reports 0.110 for the same column.</p>
<p>Two formulas are in common use. PocketStat uses the simpler one, which averages the cubed z-scores over <span class="math inline">\(n\)</span>. JASP, like SPSS, multiplies that result by a small correction for sample size, <span class="math inline">\(n^2/\big((n-1)(n-2)\big)\)</span>, which for 200 cases is 1.015. The standard errors differ for the same reason: PocketStat uses <span class="math inline">\(\sqrt{6/n} = 0.173\)</span>, and JASP uses a longer formula that gives 0.172.</p>
<p>The gap shrinks as the sample grows, and at 200 cases it changes no conclusion. Report which tool produced your figures, as you did for quartiles in chapter 1.</p>
</div>
</div>
<div class="worked-example">
<p><span class="we-label">Worked example 2.2</span></p>
<section id="deciding-whether-skew-matters" class="level3">
<h3 class="anchored" data-anchor-id="deciding-whether-skew-matters">Deciding whether skew matters</h3>
<div class="we-problem">
<p>A manager asks for “the typical spend and the typical wait” in one line of a report. JASP gives the figures in <a href="#tbl-skewness" class="quarto-xref">Table&nbsp;<span>2.3</span></a>.</p>
<p>For each variable, decide whether the skew is large enough to change the summary you report, and choose the centre and spread to quote.</p>
</div>
<div class="we-solution">
<p><strong>Waiting time:</strong> Skewness is 0.112, well under 0.5, and the ratio of 0.65 falls inside <span class="math inline">\(\pm 2\)</span>. The distribution is close to symmetric, so the mean and the standard deviation describe it well: 45.5 minutes, with a standard deviation of 11.9.</p>
<p><strong>Spending:</strong> Skewness is 0.635, in the moderate band, and the ratio of 3.69 is well beyond 2. Both rules agree that the lean is real. The median and the interquartile range describe the typical customer better: a median of 494.28 USD, with the middle half spending between 340.04 and 596.99 USD.</p>
<p>The line in the report reads:</p>
<blockquote class="blockquote">
<p>The typical customer waited 45.5 minutes (standard deviation 11.9) and spent 494 USD (median, with the middle half between 340 and 597 USD).</p>
</blockquote>
<p>Two variables in one sentence can take two different summaries, as long as the sentence names each one.</p>
</div>
</section>
</div>
<div id="tryit-2-1" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.1: Four shapes, two rules">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.1: Four shapes, two rules
</div>
</div>
<div class="callout-body-container callout-body">
<p>Four small illustrative datasets, separate from the teaching dataset, make up this exercise. Each appears in its own tab as a CSV file: a column name on the first line, then one value per line from lowest to highest.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">A. Heights</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">B. Exam scores</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">C. Income</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">D. Net worth</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Adult heights in centimetres, <span class="math inline">\(n = 25\)</span>. <a href="../assets/data/ch02/ch02-tryit-heights.csv" download="ch02-tryit-heights.csv">Download ch02-tryit-heights.csv</a></p>
<div class="csv-block">
<pre><code>Height_cm
168
170
171
172
173
174
174
175
175
175
176
176
177
177
178
178
179
180
181
182
183
184
185
186
188</code></pre>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Final exam scores out of 100, <span class="math inline">\(n = 30\)</span>. <a href="../assets/data/ch02/ch02-tryit-exam-scores.csv" download="ch02-tryit-exam-scores.csv">Download ch02-tryit-exam-scores.csv</a></p>
<div class="csv-block">
<pre><code>Exam_Score
58
62
66
68
72
75
76
78
79
80
81
82
83
84
85
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99</code></pre>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Household income in hundreds of USD a month, <span class="math inline">\(n = 25\)</span>. <a href="../assets/data/ch02/ch02-tryit-income.csv" download="ch02-tryit-income.csv">Download ch02-tryit-income.csv</a></p>
<div class="csv-block">
<pre><code>Income_Hundreds_USD
12
15
18
22
25
28
30
32
35
38
40
42
45
48
50
55
60
65
70
75
80
90
100
110
125</code></pre>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p>Personal net worth in thousands of USD, <span class="math inline">\(n = 30\)</span>. <a href="../assets/data/ch02/ch02-tryit-net-worth.csv" download="ch02-tryit-net-worth.csv">Download ch02-tryit-net-worth.csv</a></p>
<div class="csv-block">
<pre><code>Net_Worth_Thousands_USD
15
18
22
25
28
30
32
35
38
40
42
45
48
50
52
55
58
60
65
70
75
80
90
100
120
150
200
350
800
2500</code></pre>
</div>
</div>
</div>
</div>
<p>JASP reports the following for the four datasets.</p>
<div id="tbl-four-datasets" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-four-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.4: Skewness for four illustrative datasets
</figcaption>
<div aria-describedby="tbl-four-datasets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Mean</th>
<th>Median</th>
<th>Skewness</th>
<th>SE of skewness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A. Heights</td>
<td>177.48</td>
<td>177.00</td>
<td>0.288</td>
<td>0.464</td>
</tr>
<tr class="even">
<td>B. Exam scores</td>
<td>83.63</td>
<td>85.00</td>
<td>-0.696</td>
<td>0.427</td>
</tr>
<tr class="odd">
<td>C. Income</td>
<td>52.40</td>
<td>45.00</td>
<td>0.832</td>
<td>0.464</td>
</tr>
<tr class="even">
<td>D. Net worth</td>
<td>176.43</td>
<td>53.50</td>
<td>4.732</td>
<td>0.427</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ol type="1">
<li>Calculate the skewness ratio for each dataset.</li>
<li>Classify each shape with the size rule in <a href="#tbl-skew-size" class="quarto-xref">Table&nbsp;<span>2.2</span></a>, naming the direction of any skew.</li>
<li>Say where the size rule and the ratio disagree, and explain why.</li>
<li>Choose the measure of centre you would report for each dataset.</li>
</ol>
<p><strong>To check a figure in the software</strong>, load the dataset as a CSV file. JASP and PocketStat both open CSV files directly, so a CSV file is the most reliable route in.</p>
<ol type="1">
<li><strong>Get the file:</strong> Click the download link in the dataset’s tab and go straight to step 4. If the download is blocked, hover over the grey block and click the copy button at its top right.</li>
<li><strong>Paste it into a plain-text editor:</strong> On Windows, use Notepad. On a Mac, use TextEdit, and choose <strong>Format</strong>, then <strong>Make Plain Text</strong> before you paste.</li>
<li><strong>Save it with a <code>.csv</code> ending</strong>, for example <code>heights.csv</code>. In Notepad, set <strong>Save as type</strong> to <strong>All files</strong> first, or Windows saves it as <code>heights.csv.txt</code>. In TextEdit, untick any option to add a <code>.txt</code> ending.</li>
<li><strong>Open it:</strong> In JASP, open the file menu, then <strong>Open</strong>, <strong>Computer</strong>, <strong>Browse</strong>, and choose the file. In PocketStat, open the upload card on the <strong>Data</strong> tab and choose it.</li>
<li><strong>Check and run:</strong> Confirm the one column reads as <strong>scale</strong> and the row count matches the tab’s <span class="math inline">\(n\)</span>. Then run <strong>Descriptive Statistics</strong> in JASP with <strong>Skewness</strong> ticked, or <strong>Distribution shape</strong> in PocketStat.</li>
</ol>
<p>PocketStat’s skewness differs from JASP’s in the third decimal, for the reason given in the callout on the two formulas.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>A: <span class="math inline">\(0.288 \div 0.464 = 0.62\)</span>. B: <span class="math inline">\(-0.696 \div 0.427 = -1.63\)</span>. C: <span class="math inline">\(0.832 \div 0.464 = 1.79\)</span>. D: <span class="math inline">\(4.732 \div 0.427 = 11.08\)</span>.</li>
<li>A is <strong>close to symmetric</strong>, under 0.5. B is <strong>moderately skewed to the left</strong>, between 0.5 and 1 with a negative sign: a few low scores stretch the left tail. C is <strong>moderately skewed to the right</strong>: a few higher incomes stretch the right tail. D is <strong>strongly skewed to the right</strong>, far over 1, with three values, 350, 800 and 2,500, far out in the tail.</li>
<li>B and C are moderately skewed by size, and their ratios, <span class="math inline">\(-1.63\)</span> and <span class="math inline">\(1.79\)</span>, stay inside <span class="math inline">\(\pm 2\)</span>. With 25 or 30 cases the standard error is large, about 0.43 to 0.46, so the ratio misses a lean the size rule catches. The mean-against-median gap confirms the lean in both: the mean is 1.37 marks below the median for B and 7.40 above it for C.</li>
<li>A: the <strong>mean</strong>, 177.48 cm, because the shape is symmetric. B, C and D: the <strong>median</strong>. For D the mean of 176.43 is above 26 of the 30 values, and the median of 53.50 describes a typical person.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-kurtosis" class="level2">
<h2 class="anchored" data-anchor-id="sec-kurtosis">Kurtosis and the tails</h2>
<p><strong>Kurtosis</strong> measures how heavy the tails of a distribution are compared with a normal distribution of the same spread. JASP and PocketStat report <strong>excess kurtosis</strong>, which is set so that a normal distribution scores 0.</p>
<ul>
<li><strong>Positive</strong> excess kurtosis means heavier tails than normal. Extreme values turn up more often than a normal curve would predict, and the peak is usually sharper. A distribution like this is called <strong>leptokurtic</strong>.</li>
<li><strong>Negative</strong> excess kurtosis means lighter tails than normal. The cases spread more evenly across the range, the peak is flatter, and extreme values are rarer. A distribution like this is called <strong>platykurtic</strong>.</li>
</ul>
<p>Kurtosis matters to a manager because of the tails. A process with heavy tails produces more very long waits, very large orders or very bad days than its standard deviation suggests. Planning built on the normal curve will then underestimate how often the extreme case arrives.</p>
<p>Kurtosis has its own standard error, and the same ratio test applies. For 200 cases, JASP reports a standard error of kurtosis of 0.342.</p>
<div id="tbl-kurtosis" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kurtosis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.5: Excess kurtosis as JASP reports it for four variables in the teaching dataset
</figcaption>
<div aria-describedby="tbl-kurtosis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Excess kurtosis</th>
<th>SE</th>
<th>Ratio</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Waiting_Time_Mins</code></td>
<td>0.482</td>
<td>0.342</td>
<td>1.41</td>
<td>Tails slightly heavier than normal, within sampling variation</td>
</tr>
<tr class="even">
<td><code>Age</code></td>
<td>-0.599</td>
<td>0.342</td>
<td>-1.75</td>
<td>Flatter than normal, close to the limit</td>
</tr>
<tr class="odd">
<td><code>Satisfaction</code></td>
<td>-0.397</td>
<td>0.342</td>
<td>-1.16</td>
<td>Slightly flat, within sampling variation</td>
</tr>
<tr class="even">
<td><code>Spending</code></td>
<td>0.195</td>
<td>0.342</td>
<td>0.57</td>
<td>Close to normal tails</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="worked-example">
<p><span class="we-label">Worked example 2.3</span></p>
<section id="a-symmetric-variable-that-is-flat" class="level3">
<h3 class="anchored" data-anchor-id="a-symmetric-variable-that-is-flat">A symmetric variable that is flat</h3>
<div class="we-problem">
<p><code>Age</code> has a skewness of 0.038 and an excess kurtosis of -0.599, with a standard error of kurtosis of 0.342. Ages run from 22 to 52 with a mean of 35.3 and a standard deviation of 7.3.</p>
<p>Describe the shape, and decide what it means for a marketing manager planning one campaign aimed at “the typical customer’s age”.</p>
</div>
<div class="we-solution">
<p><strong>Shape:</strong> The skewness is close to 0, so age is symmetric. The kurtosis ratio is <span class="math inline">\(-0.599 \div 0.342 = -1.75\)</span>, negative and close to the limit of <span class="math inline">\(-2\)</span>. Age is flatter than a normal distribution: customers are spread fairly evenly from the mid-20s to the mid-40s, with no tall peak at 35.</p>
<p><strong>Consequence:</strong> A flat distribution has a weak centre. The mean of 35 is correct as an average, and relatively few customers are close to it. Within one standard deviation of the mean, from 28 to 42.7 years, the data contain 138 of the 200 customers, 69 per cent. The other 31 per cent are spread across the 20s and the upper 40s.</p>
<p>A campaign aimed at 35-year-olds reaches the middle of a broad group. The manager would do better to plan for a range, for example two versions aimed at the late 20s and the early 40s.</p>
</div>
</section>
</div>
<div id="tryit-2-2" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.2: Skewness and kurtosis">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.2: Skewness and kurtosis
</div>
</div>
<div class="callout-body-container callout-body">
<p>A delivery firm records the minutes each of 200 deliveries took. JASP reports a skewness of 1.34 and an excess kurtosis of 2.10. The standard errors are 0.172 and 0.342.</p>
<ol type="1">
<li>Calculate the skewness ratio and the kurtosis ratio.</li>
<li>Describe the shape in one sentence.</li>
<li>State which centre and spread you would report, and why.</li>
<li>Explain what the kurtosis figure warns the operations manager about.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Skewness ratio: <span class="math inline">\(1.34 \div 0.172 = 7.79\)</span>. Kurtosis ratio: <span class="math inline">\(2.10 \div 0.342 = 6.14\)</span>. Each is well beyond 2, so both departures exceed sampling variation.</li>
<li>Delivery times are strongly skewed to the right, with a skewness over 1, and have heavier tails than a normal distribution: most deliveries are quick, and a minority take far longer.</li>
<li>The <strong>median and the interquartile range</strong>. A skewness of 1.34 is in the strong band, so the tail of slow deliveries would pull the mean well above the typical delivery.</li>
<li>Positive excess kurtosis means very slow deliveries happen more often than a normal curve with the same standard deviation predicts. A service promise set at “mean plus two standard deviations” will be broken more often than a normal curve predicts.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="sec-boxplot-shape" class="level2">
<h2 class="anchored" data-anchor-id="sec-boxplot-shape">Boxplots and shape</h2>
<p>A boxplot shows shape through its proportions. Chapter 1 introduced it as a display of the quartiles with fences at <span class="math inline">\(1.5 \times IQR\)</span>. Read against shape, each part of the box says something.</p>
<ul>
<li><strong>The median line:</strong> In a symmetric distribution it is near the middle of the box. When it is closer to one end, the half of the box on the other side is longer, and the data are skewed that way.</li>
<li><strong>The whiskers:</strong> Whiskers of similar length suggest symmetry. A longer whisker marks the longer tail.</li>
<li><strong>The points beyond the whiskers:</strong> Cases beyond the fences appear individually. Three or more on one side only point to skew. A handful on both sides of an otherwise symmetric box point to heavy tails.</li>
</ul>
<p>For waiting time, the quartiles are 37.75, 46 and 53.25 minutes. The median is 8.25 minutes above <span class="math inline">\(Q_1\)</span> and 7.25 minutes below <span class="math inline">\(Q_3\)</span>, close to the middle of the box. Four points lie beyond the fences, two on each side, at 12 and 14 minutes and at 77 and 90. That is a symmetric box with a few distant cases on both sides.</p>
<div id="fig-boxplot-waiting" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A single vertical JASP boxplot for Waiting_Time_Mins. The box runs from about 38 to 53 minutes with the median line near 46, close to the middle. Whiskers of similar length reach 19 and 69 minutes. Two points sit below the lower whisker, at 12 and 14, and two above the upper whisker, at 77 and 90.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-waiting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/screenshots/ch02/ch02-jasp-f2-boxplot-waiting.png" class="img-fluid figure-img" alt="A single vertical JASP boxplot for Waiting_Time_Mins. The box runs from about 38 to 53 minutes with the median line near 46, close to the middle. Whiskers of similar length reach 19 and 69 minutes. Two points sit below the lower whisker, at 12 and 14, and two above the upper whisker, at 77 and 90.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-waiting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: A JASP boxplot of Waiting_Time_Mins with the four cases beyond the fences shown individually.
</figcaption>
</figure>
</div>
<div id="tryit-2-3" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.3: Read the shape from a boxplot">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.3: Read the shape from a boxplot
</div>
</div>
<div class="callout-body-container callout-body">
<p>A boxplot of order values in USD has <span class="math inline">\(Q_1 = 42\)</span>, median <span class="math inline">\(= 51\)</span> and <span class="math inline">\(Q_3 = 88\)</span>. The lower whisker reaches 18 and the upper whisker reaches 150. Seven points lie above the upper whisker and none below the lower one.</p>
<ol type="1">
<li>Is the distribution symmetric, right-skewed or left-skewed? Give two pieces of evidence.</li>
<li>Would you expect the mean to be above or below 51?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Right-skewed:</strong> The median is <span class="math inline">\(51 - 42 = 9\)</span> USD above <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(88 - 51 = 37\)</span> USD below <span class="math inline">\(Q_3\)</span>, so the upper half of the box is about four times longer. The upper whisker reaches <span class="math inline">\(150 - 88 = 62\)</span> USD beyond the box, against <span class="math inline">\(42 - 18 = 24\)</span> USD for the lower. All seven distant points lie above.</li>
<li><strong>Above 51:</strong> The tail of large orders pulls the mean up. The median stays in place.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="sec-workflow" class="level2">
<h2 class="anchored" data-anchor-id="sec-workflow">A repeatable workflow</h2>
<p>Every analysis in the rest of this module follows the same five steps, whichever tool you use. Chapter 1 took you through the first three. This chapter adds the last two, and the tutorial practises all five.</p>
<div id="tbl-workflow" class="tbl-grid quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.6: The five-step workflow used for every analysis in this module
</figcaption>
<div aria-describedby="tbl-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-grid caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>What you do</th>
<th>What it protects against</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Load</td>
<td>Open the file and confirm the row and column counts</td>
<td>A file read with the wrong delimiter, or a partial file</td>
</tr>
<tr class="even">
<td>2. Set types</td>
<td>Check every variable’s measurement level and correct it</td>
<td>A mean calculated on codes</td>
</tr>
<tr class="odd">
<td>3. Describe</td>
<td>Centre, spread and frequency tables</td>
<td>Reporting a result you have never looked at</td>
</tr>
<tr class="even">
<td>4. Look at shape</td>
<td>Histogram, boxplot, skewness, kurtosis</td>
<td>Using a summary the shape does not support</td>
</tr>
<tr class="odd">
<td>5. Annotate and export</td>
<td>Add a note to the output, then save or copy it</td>
<td>Output that nobody can interpret a week later</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Step 4 comes before any test. Chapters 4 onward choose between tests partly on shape, and a test chosen before the shape is known has been chosen blind.</p>
<p>Step 5 turns output into evidence. JASP lets you attach a written note to any table or plot in the output, and PocketStat builds a short write-up beside each result. A note written at the time, such as “Satisfaction piles up at 5.00, so the left tail is partly a ceiling effect”, saves the reader from rediscovering it, and saves you from forgetting it.</p>
<p>The <a href="week02-reference.html#sec-software">reference page</a> lists the exact menu steps for both tools, and the <a href="week02-tutorial.html">tutorial</a> takes you through them at the machine.</p>
</section>
<section id="section-summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-summary">Section summary</h2>
<p>A value’s position depends on its distance from the centre, the spread that distance is measured against, and the shape of the distribution. A histogram shows the shape through its peaks, its symmetry and its tails. Skewness measures the lean and kurtosis measures the weight of the tails, and each is judged by its size and by its ratio to its standard error. A scale with a maximum can create a ceiling effect that looks like skew. The five-step workflow puts the look at shape before any summary is chosen.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Next:</strong> <a href="week02-part2.html">Part 2, the normal curve and z-scores</a> covers the normal distribution, the empirical rule, Chebyshev’s rule and the z-score.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mohammedalisharafuddin\.github\.io\/dmm-textbook");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../weeks/week01-independent-study.html" class="pagination-link" aria-label="Independent study">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Independent study</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../weeks/week02-part2.html" class="pagination-link" aria-label="Part 2: The normal curve and z-scores">
        <span class="nav-page-text"><span class="chapter-title">Part 2: The normal curve and z-scores</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>
