<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="normal distribution, empirical rule, 68-95-99.7 rule, Chebyshev’s rule, z-score, standardised score, unusual values">
<meta name="description" content="Chapter 2, part 2. The normal distribution, the empirical rule, Chebyshev’s rule, z-scores, and how to judge a value as typical, unusual or extreme.">

<title>Part 2: The normal curve and z-scores – Decision Making for Management</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../weeks/week02-part3.html" rel="next">
<link href="../weeks/week02.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f4b9810437ab3d39bd583d8cb295f5db.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Structured data for search and answer engines. The book is CC BY, so a
     model that cites it can say so. DefinedTermSet mirrors the Key terms
     section, whose entries carry the section ids these URLs point at. -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Book",
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/#book",
      "name": "Decision Making for Management",
      "alternateName": "A Student Textbook for Data-Informed Managerial Judgement",
      "inLanguage": "en-GB",
      "learningResourceType": "textbook",
      "educationalLevel": "undergraduate",
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "author": {
        "@type": "Person",
        "name": "Mohammed Ali Sharafuddin",
        "affiliation": {
          "@type": "CollegeOrUniversity",
          "name": "Qasim Ibrahim School of Business, Villa College"
        }
      },
      "educationalUse": ["instruction", "self study"],
      "audience": {
        "@type": "EducationalAudience",
        "educationalRole": "student"
      },
      "usageInfo": "https://mohammedalisharafuddin.github.io/dmm-textbook/front-matter/ai-use.html",
      "about": [
        "Business statistics",
        "Descriptive statistics",
        "Data-informed decision making"
      ]
    },
    {
      "@type": ["Chapter", "LearningResource"],
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#chapter",
      "name": "Data, Measurement Scales, and Descriptive Statistics",
      "position": 1,
      "isPartOf": { "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/#book" },
      "inLanguage": "en-GB",
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "educationalLevel": "undergraduate",
      "learningResourceType": "chapter",
      "timeRequired": "PT9H",
      "educationalUse": ["instruction", "self study"],
      "assessmentType": ["formative exit check", "checkpoint quiz", "tutorial upload"],
      "usageInfo": "https://mohammedalisharafuddin.github.io/dmm-textbook/front-matter/ai-use.html",
      "educationalAlignment": {
        "@type": "AlignmentObject",
        "alignmentType": "teaches",
        "targetName": "Descriptive statistics for management decisions"
      },
      "teaches": [
        "Explain why a manager describes evidence before acting on it",
        "Distinguish a case, a variable, an observation and a value in a real dataset",
        "Separate a population from a sample, and a parameter from a statistic",
        "Say what descriptive statistics can establish and what only inference can",
        "Classify a variable as nominal, ordinal, interval or ratio, and as discrete or continuous",
        "Identify which variable is independent and which is dependent in a stated question",
        "Build and read frequency, relative frequency, grouped and cumulative frequency tables",
        "Choose a graph that suits the variable type and the question",
        "Calculate and interpret the mean, median, mode, range, variance, standard deviation, quartiles and the interquartile range",
        "Recognise a misleading summary or display and say why it misleads"
      ]
    },
    {
      "@type": "DefinedTermSet",
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#key-terms",
      "name": "Key terms, Chapter 1",
      "hasDefinedTerm": [
        { "@type": "DefinedTerm", "name": "Case", "description": "The unit the data describe.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-cases" },
        { "@type": "DefinedTerm", "name": "Variable", "description": "A characteristic measured on each case.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-cases" },
        { "@type": "DefinedTerm", "name": "Population", "description": "Every case of interest.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Sample", "description": "The subset of the population actually measured.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Parameter", "description": "A number describing a population.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Statistic", "description": "A number describing a sample.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01.html#sec-population" },
        { "@type": "DefinedTerm", "name": "Nominal", "description": "Named categories with no order. You may count them, find the mode and take proportions.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Ordinal", "description": "Ordered categories where the size of the gaps between them is unknown.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Interval", "description": "Numeric with equal gaps and a zero placed by convention, so ratios have no meaning.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Ratio", "description": "Numeric with equal gaps and a true zero, so ratios are meaningful.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part2.html#sec-scales" },
        { "@type": "DefinedTerm", "name": "Mean", "description": "The sum of all values divided by how many there are.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-centre" },
        { "@type": "DefinedTerm", "name": "Median", "description": "The middle value once the data are in order.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-centre" },
        { "@type": "DefinedTerm", "name": "Mode", "description": "The value that occurs most often, read off a frequency table.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-centre" },
        { "@type": "DefinedTerm", "name": "Standard deviation", "description": "The square root of the variance, in the original units of the data.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-spread" },
        { "@type": "DefinedTerm", "name": "Interquartile range", "description": "The third quartile minus the first, the spread of the middle half.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-quartiles" },
        { "@type": "DefinedTerm", "name": "Outlier", "description": "A value beyond 1.5 times the interquartile range from the nearer quartile.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week01-part3.html#sec-shape" }
      ]
    },
    {
      "@type": ["Chapter", "LearningResource"],
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#chapter",
      "name": "Introduction to JASP and the Normal Distribution",
      "position": 2,
      "isPartOf": { "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/#book" },
      "inLanguage": "en-GB",
      "license": "https://creativecommons.org/licenses/by/4.0/",
      "educationalLevel": "undergraduate",
      "learningResourceType": "chapter",
      "timeRequired": "PT9H",
      "educationalUse": ["instruction", "self study"],
      "assessmentType": ["formative exit check", "checkpoint quiz", "tutorial upload"],
      "usageInfo": "https://mohammedalisharafuddin.github.io/dmm-textbook/front-matter/ai-use.html",
      "educationalAlignment": {
        "@type": "AlignmentObject",
        "alignmentType": "teaches",
        "targetName": "The normal distribution and z-scores for management decisions"
      },
      "teaches": [
        "Describe the shape of a distribution from a histogram and a boxplot, naming its peaks, its symmetry and its tails",
        "Interpret skewness and kurtosis, and judge each against its standard error",
        "Follow a repeatable workflow in JASP or PocketStat from loading a file to an annotated output",
        "State the properties of the normal distribution and use the empirical rule to estimate the share of cases within one, two and three standard deviations of the mean",
        "Apply Chebyshev's rule when the shape of a distribution is unknown or clearly non-normal",
        "Calculate a z-score, convert a z-score back into the original units, and use z-scores to compare values measured in different units",
        "Classify a value as typical, unusual or extreme from its z-score, and explain in plain language what that means for a manager",
        "Use the standard normal table to find the share of cases above, below or between two values, and the value that marks a given percentile",
        "Judge whether a variable is close enough to normal for the normal model, using a histogram, a Q-Q plot, skewness, kurtosis and the Shapiro-Wilk test",
        "Recognise when the normal model gives impossible or distorted answers, and report the alternative"
      ]
    },
    {
      "@type": "DefinedTermSet",
      "@id": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#key-terms",
      "name": "Key terms, Chapter 2",
      "hasDefinedTerm": [
        { "@type": "DefinedTerm", "name": "Distribution", "description": "The values a variable takes, and how often each occurs.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-position" },
        { "@type": "DefinedTerm", "name": "Ceiling effect", "description": "Cases piled up at the highest value a scale allows, which cuts off the right tail.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-shape-reading" },
        { "@type": "DefinedTerm", "name": "Skewness", "description": "How far a distribution leans to one side. Positive for a longer right tail, negative for a longer left tail.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-skewness" },
        { "@type": "DefinedTerm", "name": "Standard error", "description": "How much a statistic would typically vary from one sample to the next.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-skewness" },
        { "@type": "DefinedTerm", "name": "Kurtosis", "description": "How heavy the tails of a distribution are compared with a normal distribution, reported as excess kurtosis with 0 for normal.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02.html#sec-kurtosis" },
        { "@type": "DefinedTerm", "name": "Normal distribution", "description": "A symmetric bell-shaped model fixed by its mean and standard deviation, whose areas are shares of cases.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-normal" },
        { "@type": "DefinedTerm", "name": "Empirical rule", "description": "In a normal distribution about 68, 95 and 99.7 per cent of cases lie within one, two and three standard deviations of the mean.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-empirical" },
        { "@type": "DefinedTerm", "name": "Chebyshev's rule", "description": "For any distribution, at least 1 minus 1 over k squared of the cases lie within k standard deviations of the mean.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-chebyshev" },
        { "@type": "DefinedTerm", "name": "z-score", "description": "How many standard deviations a value lies above or below the mean.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part2.html#sec-zscores" },
        { "@type": "DefinedTerm", "name": "Standard normal distribution", "description": "The normal distribution with a mean of 0 and a standard deviation of 1.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part3.html#sec-standard-normal" },
        { "@type": "DefinedTerm", "name": "Q-Q plot", "description": "A plot of sorted data against the values a normal distribution predicts for each position. Normal data lie on a straight line.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part3.html#sec-normality" },
        { "@type": "DefinedTerm", "name": "Shapiro-Wilk test", "description": "A test of how closely data follow the pattern a normal distribution would produce. Its verdict depends heavily on sample size.", "url": "https://mohammedalisharafuddin.github.io/dmm-textbook/weeks/week02-part3.html#sec-normality" }
      ]
    }
  ]
}
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/fonts.css">
<link rel="stylesheet" href="../assets/css/typography.css">
<link rel="stylesheet" href="../assets/css/student-book.css">
<meta property="og:title" content="Part 2: The normal curve and z-scores – Decision Making for Management">
<meta property="og:description" content="A CC BY undergraduate textbook that teaches descriptive and inferential statistics through management decisions, using JASP and PocketStat.">
<meta property="og:image" content="https://mohammedalisharafuddin.github.io/dmm-textbook/assets/images/figures/ch02/ch02-fig-empirical-rule.png">
<meta property="og:site_name" content="Decision Making for Management">
<meta property="og:locale" content="en_GB">
<meta property="og:image:alt" content="A symmetric bell curve with its horizontal axis marked from minus 3 to plus 3 standard deviations, and beneath each mark the matching waiting time in minutes: 9.7, 21.6, 33.5, 45.5, 57.4, 69.3 and 81.2. The central band from minus 1 to plus 1 is shaded darkest, the bands out to plus and minus 2 lighter, and the bands out to plus and minus 3 lightest. Brackets above the curve read 68 per cent within 1 SD, 95 per cent within 2 SD, and 99.7 per cent within 3 SD.">
<meta property="og:image:height" content="880">
<meta property="og:image:width" content="1600">
<meta name="twitter:title" content="Part 2: The normal curve and z-scores – Decision Making for Management">
<meta name="twitter:description" content="A CC BY undergraduate textbook that teaches descriptive and inferential statistics through management decisions, using JASP and PocketStat.">
<meta name="twitter:image" content="https://mohammedalisharafuddin.github.io/dmm-textbook/assets/images/figures/ch02/ch02-fig-empirical-rule.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image:alt" content="A symmetric bell curve with its horizontal axis marked from minus 3 to plus 3 standard deviations, and beneath each mark the matching waiting time in minutes: 9.7, 21.6, 33.5, 45.5, 57.4, 69.3 and 81.2. The central band from minus 1 to plus 1 is shaded darkest, the bands out to plus and minus 2 lighter, and the bands out to plus and minus 3 lightest. Brackets above the curve read 68 per cent within 1 SD, 95 per cent within 2 SD, and 99.7 per cent within 3 SD.">
<meta name="twitter:image-height" content="880">
<meta name="twitter:image-width" content="1600">
<meta name="dmm-crossref-renumbered" content="1"></head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../weeks/week02.html">Chapter 2: Introduction to JASP and the Normal Distribution</a></li><li class="breadcrumb-item"><a href="../weeks/week02-part2.html"><span class="chapter-title">Part 2: The normal curve and z-scores</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Decision Making for Management</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decision Making for Management</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/copyright.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Copyright and Attribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/ai-use.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using AI on This Module</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/how-to-use-this-book.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use This Book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/software-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software Guide</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../front-matter/dataset-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dataset Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Chapter 1: Data, Measurement Scales, and Descriptive Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 1: Foundations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-part2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 2: Variables and displays</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-part3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 3: Centre and spread</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-reference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Running the analysis, and chapter reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial: First descriptive statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week01-independent-study.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Independent study</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Chapter 2: Introduction to JASP and the Normal Distribution</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 1: The shape of a distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-part2.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Part 2: The normal curve and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-part3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 3: Areas, percentiles and checking normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-reference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Running the analysis, and chapter reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-tutorial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tutorial: JASP setup, normality, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../weeks/week02-independent-study.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Independent study</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-normal" id="toc-sec-normal" class="nav-link active" data-scroll-target="#sec-normal">The normal distribution</a>
  <ul class="collapse">
  <li><a href="#properties-of-the-normal-curve" id="toc-properties-of-the-normal-curve" class="nav-link" data-scroll-target="#properties-of-the-normal-curve">Properties of the normal curve</a></li>
  <li><a href="#many-curves-one-shape" id="toc-many-curves-one-shape" class="nav-link" data-scroll-target="#many-curves-one-shape">Many curves, one shape</a></li>
  </ul></li>
  <li><a href="#sec-empirical" id="toc-sec-empirical" class="nav-link" data-scroll-target="#sec-empirical">The empirical rule</a>
  <ul class="collapse">
  <li><a href="#the-rule-against-real-data" id="toc-the-rule-against-real-data" class="nav-link" data-scroll-target="#the-rule-against-real-data">The rule against real data</a></li>
  </ul></li>
  <li><a href="#sec-chebyshev" id="toc-sec-chebyshev" class="nav-link" data-scroll-target="#sec-chebyshev">Chebyshev’s rule for any shape</a></li>
  <li><a href="#sec-zscores" id="toc-sec-zscores" class="nav-link" data-scroll-target="#sec-zscores">z-scores</a>
  <ul class="collapse">
  <li><a href="#calculating-a-z-score" id="toc-calculating-a-z-score" class="nav-link" data-scroll-target="#calculating-a-z-score">Calculating a z-score</a></li>
  <li><a href="#from-a-z-score-back-to-the-original-units" id="toc-from-a-z-score-back-to-the-original-units" class="nav-link" data-scroll-target="#from-a-z-score-back-to-the-original-units">From a z-score back to the original units</a></li>
  <li><a href="#sec-z-calculator" id="toc-sec-z-calculator" class="nav-link" data-scroll-target="#sec-z-calculator">Check your working with the z-score calculator</a></li>
  </ul></li>
  <li><a href="#sec-unusual" id="toc-sec-unusual" class="nav-link" data-scroll-target="#sec-unusual">Typical, unusual and extreme values</a>
  <ul class="collapse">
  <li><a href="#the-unusual-waits-in-the-teaching-dataset" id="toc-the-unusual-waits-in-the-teaching-dataset" class="nav-link" data-scroll-target="#the-unusual-waits-in-the-teaching-dataset">The unusual waits in the teaching dataset</a></li>
  </ul></li>
  <li><a href="#sec-compare-z" id="toc-sec-compare-z" class="nav-link" data-scroll-target="#sec-compare-z">Comparing values in different units</a></li>
  <li><a href="#section-summary" id="toc-section-summary" class="nav-link" data-scroll-target="#section-summary">Section summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../weeks/week02.html">Chapter 2: Introduction to JASP and the Normal Distribution</a></li><li class="breadcrumb-item"><a href="../weeks/week02-part2.html"><span class="chapter-title">Part 2: The normal curve and z-scores</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Part 2: The normal curve and z-scores</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>normal distribution, empirical rule, 68-95-99.7 rule, Chebyshev’s rule, z-score, standardised score, unusual values</p>
  </div>
</div>

</header>


<p>Part 1 showed you how to read the shape of a distribution. Part 2 introduces the shape that most of statistics measures against, the normal distribution, and uses it to place a single value inside a distribution with one number, the z-score.</p>
<section id="sec-normal" class="level2">
<h2 class="anchored" data-anchor-id="sec-normal">The normal distribution</h2>
<p>The <strong>normal distribution</strong> is a symmetric, bell-shaped curve that describes how values spread around a centre when many small, independent influences add together. A customer’s waiting time is a sum of small influences. These include how many people arrived just before, how long each transaction took, and whether a colleague was on a break. When enough of them combine, the result tends towards the bell shape.</p>
<p>The normal curve is a theoretical model. You can think of it as an idealised histogram, drawn for an infinite number of cases with bars of zero width. No real dataset follows it exactly. Many come close enough for the model to answer practical questions, and part 3 shows you how to judge whether yours does.</p>
<section id="properties-of-the-normal-curve" class="level3">
<h3 class="anchored" data-anchor-id="properties-of-the-normal-curve">Properties of the normal curve</h3>
<p>Six properties define the normal distribution:</p>
<ol type="1">
<li>It has one peak, at the mean.</li>
<li>It is symmetric about the mean, so the mean, the median and the mode are equal.</li>
<li>Its tails extend in both directions without limit, and they thin out quickly. Values far from the mean are possible and rare.</li>
<li>Two numbers define it completely. The mean, <span class="math inline">\(\mu\)</span>, determines the peak location, and the standard deviation, <span class="math inline">\(\sigma\)</span>, determines the width of the curve.</li>
<li>The total area under the curve is 1, which stands for 100 per cent of the cases.</li>
<li>The area under the curve between two values equals the share of cases that fall between them.</li>
</ol>
<p>Property 4 gives the notation. A variable <span class="math inline">\(X\)</span> that follows a normal distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> is written</p>
<p><span class="math display">\[X \sim N(\mu, \sigma)\]</span></p>
<p>and read “X is normally distributed with mean mu and standard deviation sigma”. Some books write the variance, <span class="math inline">\(\sigma^2\)</span>, in the second position. Check which one a source uses before you copy a figure from it.</p>
<p>Property 6 provides the most practical value. The height of the curve at a single point is hard to interpret on its own. The <strong>area</strong> under the curve is a proportion, and a proportion is something a manager can use: the share of customers who wait longer than an hour, or the share of parcels that weigh less than the label says.</p>
</section>
<section id="many-curves-one-shape" class="level3">
<h3 class="anchored" data-anchor-id="many-curves-one-shape">Many curves, one shape</h3>
<p>Changing the mean slides the curve along the axis. Changing the standard deviation stretches or squeezes it. A branch with a mean wait of 45 minutes and a standard deviation of 12 has a wide, low curve. A branch with the same mean and a standard deviation of 3 has a narrow, tall one. The total area under each is still 1.</p>
<p>Every normal curve has the same shape once its horizontal axis is measured in standard deviations from the mean. That fact makes the rest of this chapter possible. One set of proportions, worked out once for a single reference curve, applies to every normal distribution there is.</p>
</section>
</section>
<section id="sec-empirical" class="level2">
<h2 class="anchored" data-anchor-id="sec-empirical">The empirical rule</h2>
<p>The <strong>empirical rule</strong> states the share of cases that fall within one, two and three standard deviations of the mean in any normal distribution:</p>
<ul>
<li>about <strong>68 per cent</strong> lie within one standard deviation of the mean</li>
<li>about <strong>95 per cent</strong> lie within two standard deviations</li>
<li>about <strong>99.7 per cent</strong> lie within three standard deviations</li>
</ul>
<p>It is also called the 68-95-99.7 rule.</p>
<div id="fig-empirical-rule" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A symmetric bell curve with its horizontal axis marked from minus 3 to plus 3 standard deviations, and beneath each mark the matching waiting time in minutes: 9.7, 21.6, 33.5, 45.5, 57.4, 69.3 and 81.2. The central band from minus 1 to plus 1 is shaded darkest, the bands out to plus and minus 2 lighter, and the bands out to plus and minus 3 lightest. Brackets above the curve read 68 per cent within 1 SD, 95 per cent within 2 SD, and 99.7 per cent within 3 SD.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-empirical-rule-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/figures/ch02/ch02-fig-empirical-rule.png" class="img-fluid figure-img" alt="A symmetric bell curve with its horizontal axis marked from minus 3 to plus 3 standard deviations, and beneath each mark the matching waiting time in minutes: 9.7, 21.6, 33.5, 45.5, 57.4, 69.3 and 81.2. The central band from minus 1 to plus 1 is shaded darkest, the bands out to plus and minus 2 lighter, and the bands out to plus and minus 3 lightest. Brackets above the curve read 68 per cent within 1 SD, 95 per cent within 2 SD, and 99.7 per cent within 3 SD.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-empirical-rule-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: The empirical rule on a normal curve, with the axis marked in standard deviations and in the waiting times of the teaching dataset.
</figcaption>
</figure>
</div>
<p>Because the curve is symmetric, each share splits evenly between the two sides. If 95 per cent lie within two standard deviations, the remaining 5 per cent split into 2.5 per cent above <span class="math inline">\(\mu + 2\sigma\)</span> and 2.5 per cent below <span class="math inline">\(\mu - 2\sigma\)</span>. The same reasoning puts 16 per cent above <span class="math inline">\(\mu + \sigma\)</span>, because <span class="math inline">\((100 - 68) \div 2 = 16\)</span>.</p>
<section id="the-rule-against-real-data" class="level3">
<h3 class="anchored" data-anchor-id="the-rule-against-real-data">The rule against real data</h3>
<p>Waiting time in the teaching dataset has a mean of 45.46 minutes and a standard deviation of 11.91. <a href="#tbl-empirical-waiting" class="quarto-xref">Table&nbsp;<span>2.7</span></a> compares what the rule predicts for 200 customers with what the data show.</p>
<div id="tbl-empirical-waiting" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-empirical-waiting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.7: The empirical rule against the 200 waiting times in the teaching dataset
</figcaption>
<div aria-describedby="tbl-empirical-waiting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<thead>
<tr class="header">
<th>Band</th>
<th>Minutes</th>
<th>Rule predicts</th>
<th>Data holds</th>
<th>Data share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Within 1 SD</td>
<td>33.5 to 57.4</td>
<td>136</td>
<td>133</td>
<td>66.5%</td>
</tr>
<tr class="even">
<td>Within 2 SD</td>
<td>21.6 to 69.3</td>
<td>190</td>
<td>193</td>
<td>96.5%</td>
</tr>
<tr class="odd">
<td>Within 3 SD</td>
<td>9.7 to 81.2</td>
<td>199</td>
<td>199</td>
<td>99.5%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The agreement is close. Chapter 1 found 133 customers within one standard deviation and said this chapter would make that figure precise: the rule predicts 68 per cent, and the data show 66.5 per cent.</p>
<div class="worked-example">
<p><span class="we-label">Worked example 2.4</span></p>
<section id="using-the-empirical-rule-for-a-service-promise" class="level3">
<h3 class="anchored" data-anchor-id="using-the-empirical-rule-for-a-service-promise">Using the empirical rule for a service promise</h3>
<div class="we-problem">
<p>Waiting times have a mean of 45.5 minutes and a standard deviation of 11.9, and the distribution is close to normal.</p>
<p>Use the empirical rule to estimate the share of customers who wait longer than 69.3 minutes, and the share who wait between 33.6 and 69.3 minutes. Then check the first estimate against the data.</p>
</div>
<div class="we-solution">
<p><strong>Longer than 69.3 minutes:</strong> <span class="math inline">\(69.3 = 45.5 + 2 \times 11.9\)</span>, so this is the tail beyond two standard deviations above the mean. The rule puts 95 per cent within two standard deviations, and the other 5 per cent split evenly between the two tails:</p>
<p><span class="math display">\[\frac{100\% - 95\%}{2} = 2.5\%\]</span></p>
<p>About 2.5 per cent, or 5 of 200 customers.</p>
<p><strong>Between 33.6 and 69.3 minutes:</strong> <span class="math inline">\(33.6 = 45.5 - 11.9\)</span>, one standard deviation below the mean. The range runs from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+2\)</span> standard deviations, so combine half of each band:</p>
<p><span class="math display">\[\frac{68\%}{2} + \frac{95\%}{2} = 34\% + 47.5\% = 81.5\%\]</span></p>
<p>About 81.5 per cent of customers.</p>
<p><strong>Check against the data:</strong> Two customers waited longer than 69.3 minutes, at 77 and 90. The rule predicted about 5. Five customers fall more than two standard deviations <em>below</em> the mean, so the two tails contain 7 between them against a prediction of 10. The rule describes the centre of this distribution very well and its thin tails a little less well, which is typical of a real dataset. The small numbers in the tails are also where chance has the most influence.</p>
</div>
</section>
</div>
<div id="tryit-2-4" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.4: Apply the empirical rule">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.4: Apply the empirical rule
</div>
</div>
<div class="callout-body-container callout-body">
<p>A packing line fills bags of rice with a mean of 1,000 grams and a standard deviation of 4 grams. The fill weights are close to normal.</p>
<ol type="1">
<li>Between which two weights do about 95 per cent of bags fall?</li>
<li>What share of bags weigh more than 1,004 grams?</li>
<li>What share weigh less than 988 grams?</li>
<li>The label promises 992 grams or more. Roughly how many bags in 10,000 break that promise?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Within two standard deviations: <span class="math inline">\(1{,}000 \pm 2 \times 4\)</span>, so <strong>992 to 1,008 grams</strong>.</li>
<li><span class="math inline">\(1{,}004 = 1{,}000 + 4\)</span>, one standard deviation above. The share above is $(100% - 68%) = $ <strong>16 per cent</strong>.</li>
<li><span class="math inline">\(988 = 1{,}000 - 3 \times 4\)</span>, three standard deviations below. The share beyond three standard deviations on one side is $(100% - 99.7%) = $ <strong>0.15 per cent</strong>.</li>
<li><span class="math inline">\(992\)</span> is two standard deviations below the mean, so 2.5 per cent of bags weigh less. In 10,000 bags that is <strong>about 250</strong>. The manager would raise the mean fill or tighten the standard deviation until the share was acceptable.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-chebyshev" class="level2">
<h2 class="anchored" data-anchor-id="sec-chebyshev">Chebyshev’s rule for any shape</h2>
<p>The empirical rule applies only to distributions close to normal. <strong>Chebyshev’s rule</strong> applies to every distribution, regardless of its shape. For any number <span class="math inline">\(k\)</span> greater than 1, at least</p>
<p><span class="math display">\[1 - \frac{1}{k^2}\]</span></p>
<p>of the cases lie within <span class="math inline">\(k\)</span> standard deviations of the mean.</p>
<div id="tbl-chebyshev" class="tbl-grid quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chebyshev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.8: Chebyshev’s guarantee against the empirical rule
</figcaption>
<div aria-describedby="tbl-chebyshev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-grid caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Distance from the mean</th>
<th>Chebyshev guarantees at least</th>
<th>Empirical rule, if normal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2 standard deviations</td>
<td><span class="math inline">\(1 - 1/4 = 75\%\)</span></td>
<td>95%</td>
</tr>
<tr class="even">
<td>3 standard deviations</td>
<td><span class="math inline">\(1 - 1/9 = 88.9\%\)</span></td>
<td>99.7%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Chebyshev’s figures are floors. The true share is almost always higher, and for a normal distribution it is much higher. The rule gives you a guarantee you can use when the shape is unknown, skewed or heavy-tailed, and it trades precision for that guarantee.</p>
<p><code>Spending</code> shows why the guarantee matters. Its standard deviation is 256.84 USD around a mean of 505.65. Two standard deviations either side runs from <span class="math inline">\(-8.03\)</span> to 1,019.33 USD. The data place 190 of 200 customers in that band, 95 per cent, which matches the empirical rule exactly. The match hides a problem: all 10 customers outside the band are high spenders, and none are low. The empirical rule assumes the outside share splits evenly between the two tails, and here it splits 10 to 0. The lower limit, <span class="math inline">\(-8.03\)</span> USD, is a spend no customer can make.</p>
<p>For a skewed variable, the percentages from the empirical rule can look right while the story they tell about the tails is misleading. Chebyshev’s floor of 75 per cent is safe for any shape, and it makes no claim about which side the outside cases fall on.</p>
<div id="tryit-2-5" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.5: Chebyshev's rule">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.5: Chebyshev’s rule
</div>
</div>
<div class="callout-body-container callout-body">
<p>Monthly insurance claims at a small firm have a mean of 12,000 USD and a standard deviation of 3,000. The distribution is strongly right-skewed.</p>
<ol type="1">
<li>Using Chebyshev’s rule, what share of months at least fall between 6,000 and 18,000 USD?</li>
<li>What share at least fall within 2.5 standard deviations of the mean, and what range of claims is that?</li>
<li>Why would the empirical rule be a poor choice here?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(6{,}000\)</span> and <span class="math inline">\(18{,}000\)</span> are <span class="math inline">\(12{,}000 \pm 2 \times 3{,}000\)</span>, so <span class="math inline">\(k = 2\)</span>. At least $1 - 1/2^2 = $ <strong>75 per cent</strong> of months.</li>
<li><span class="math inline">\(k = 2.5\)</span>: at least $1 - 1/2.5^2 = 1 - 1/6.25 = 1 - 0.16 = $ <strong>84 per cent</strong> of months, in the range <span class="math inline">\(12{,}000 \pm 2.5 \times 3{,}000\)</span>, from <strong>4,500 to 19,500 USD</strong>.</li>
<li>The empirical rule assumes a normal, symmetric shape. With strong right skew, the months outside two standard deviations will sit almost entirely on the high side, and the rule would report the split as even. Chebyshev’s floor makes no assumption about shape.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="sec-zscores" class="level2">
<h2 class="anchored" data-anchor-id="sec-zscores">z-scores</h2>
<p>A <strong>z-score</strong>, also called a <strong>standardised score</strong>, states how many standard deviations a value lies from the mean. For a value <span class="math inline">\(x\)</span> in a sample with mean <span class="math inline">\(\bar{x}\)</span> and standard deviation <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[z = \frac{x - \bar{x}}{s}\]</span></p>
<p>For a population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> the formula takes the Greek letters, <span class="math inline">\(z = (x - \mu) / \sigma\)</span>. The arithmetic is the same.</p>
<p>Three facts follow from the formula:</p>
<ul>
<li><strong>The sign gives the direction.</strong> A positive z-score lies above the mean and a negative one lies below. A z-score of 0 is the mean itself.</li>
<li><strong>The size gives the distance, in standard deviations.</strong> A z-score of <span class="math inline">\(-1.5\)</span> lies one and a half standard deviations below the mean.</li>
<li><strong>The units cancel.</strong> The numerator and the denominator are both in minutes, or both in USD, so a z-score has no units. That lets you compare values measured on different scales, which <a href="#sec-compare-z" class="quarto-xref"><span>Comparing values in different units</span></a> uses.</li>
</ul>
<p>Converting every value in a column to its z-score is called <strong>standardising</strong> the column. A standardised column always has a mean of 0 and a standard deviation of 1, whatever its original units.</p>
<section id="calculating-a-z-score" class="level3">
<h3 class="anchored" data-anchor-id="calculating-a-z-score">Calculating a z-score</h3>
<p>For respondent 58, who waited 77 minutes:</p>
<p><span class="math display">\[z = \frac{77 - 45.455}{11.905} = \frac{31.545}{11.905} = 2.65\]</span></p>
<p>Respondent 58 waited 2.65 standard deviations longer than the average customer.</p>
</section>
<section id="from-a-z-score-back-to-the-original-units" class="level3">
<h3 class="anchored" data-anchor-id="from-a-z-score-back-to-the-original-units">From a z-score back to the original units</h3>
<p>Rearranging the formula turns a z-score back into a value:</p>
<p><span class="math display">\[x = \bar{x} + z \times s\]</span></p>
<p>This answers questions that start from a position and ask for a value. For example: the wait that falls 1.5 standard deviations below the mean is</p>
<p><span class="math display">\[x = 45.455 + (-1.5) \times 11.905 = 45.455 - 17.858 = 27.6 \text{ minutes}\]</span></p>
<div class="worked-example">
<p><span class="we-label">Worked example 2.5</span></p>
<section id="standardising-the-first-five-customers" class="level3">
<h3 class="anchored" data-anchor-id="standardising-the-first-five-customers">Standardising the first five customers</h3>
<div class="we-problem">
<p>The first five waiting times in the teaching dataset are 28, 39, 37, 48 and 61 minutes. The full column has a mean of 45.455 and a standard deviation of 11.905.</p>
<p>Calculate the z-score of each wait against the full column, and say in plain language what the largest one means.</p>
</div>
<div class="we-solution">
<p>Subtract the mean, then divide by the standard deviation.</p>
<div id="tbl-first-five-z" class="tbl-calc quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-first-five-z-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.9: z-scores for the first five waiting times, measured against all 200 customers
</figcaption>
<div aria-describedby="tbl-first-five-z-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-calc caption-top table">
<thead>
<tr class="header">
<th>Respondent</th>
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(x - \bar{x}\)</span></th>
<th><span class="math inline">\(z\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>28</td>
<td>-17.455</td>
<td>-1.47</td>
</tr>
<tr class="even">
<td>2</td>
<td>39</td>
<td>-6.455</td>
<td>-0.54</td>
</tr>
<tr class="odd">
<td>3</td>
<td>37</td>
<td>-8.455</td>
<td>-0.71</td>
</tr>
<tr class="even">
<td>4</td>
<td>48</td>
<td>2.545</td>
<td>0.21</td>
</tr>
<tr class="odd">
<td>5</td>
<td>61</td>
<td>15.545</td>
<td>1.31</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Respondent 1 was served faster than most, at 1.47 standard deviations below the average. Respondents 2, 3 and 4 fall within one standard deviation of the mean, in the band that contains about two customers in three.</p>
<p>The largest z-score, in size, is respondent 1’s. The largest above the mean is respondent 5’s:</p>
<blockquote class="blockquote">
<p>Respondent 5 waited 61 minutes, 1.31 standard deviations longer than the average customer. That is a long wait, and still a typical one: roughly one customer in ten waits this long or longer.</p>
</blockquote>
<p>The empirical rule brackets the “one in ten”. Sixteen per cent of customers lie more than one standard deviation above the mean and 2.5 per cent lie more than two above, so a wait 1.31 standard deviations above falls between the two. The data agree: 19 of the 200 customers, 9.5 per cent, waited 61 minutes or longer. Part 3 shows how to find the share exactly.</p>
<p>Worked example 1.10 in chapter 1 used the same five values to find a standard deviation of 12.50 <em>within</em> the five. The z-scores here use the mean and standard deviation of <em>all 200</em>, because the question is where each customer falls in the full branch.</p>
</div>
</section>
</div>
</section>
<section id="sec-z-calculator" class="level3">
<h3 class="anchored" data-anchor-id="sec-z-calculator">Check your working with the z-score calculator</h3>
<p>The calculator below opens on respondent 58: a wait of 77 minutes against the mean of 45.455 and the standard deviation of 11.905. Work each z-score by hand first, then use the calculator to check it.</p>
<div class="tool-embed">
<iframe src="https://flairmi.com/toolkit/z-score-calculator-embed.html?x=77&amp;mean=45.455&amp;sd=11.905" title="Z-score calculator, opened on a wait of 77 minutes" width="100%" height="820" loading="lazy" style="border:1px solid #d1d9e6; border-radius:6px;">
</iframe>
<p>If the panel above stays blank, open the <a href="https://flairmi.com/toolkit/z-score-calculator.html?x=77&amp;mean=45.455&amp;sd=11.905">z-score calculator in a new tab</a>.</p>
</div>
<p>Three checks to run:</p>
<ol type="1">
<li><strong>One value:</strong> Leave the calculator as it opens. The working line shows <span class="math inline">\((77 - 45.455) / 11.905 = 2.65\)</span>, the figure you calculated for respondent 58.</li>
<li><strong>Five values:</strong> Replace 77 with <code>28, 39, 37, 48, 61</code>. The table lists the five z-scores from
<ol class="example" type="1">
<li></li>
</ol></li>
<li><strong>Back to minutes:</strong> Choose <strong>A value from a z-score</strong> and enter <span class="math inline">\(-1.5\)</span>. The answer is 27.6 minutes, the wait you found by rearranging the formula.</li>
</ol>
<p>The calculator also reports an area below and an area above each z-score. Part 3 explains those areas and how to read them from a table.</p>
</section>
</section>
<section id="sec-unusual" class="level2">
<h2 class="anchored" data-anchor-id="sec-unusual">Typical, unusual and extreme values</h2>
<p>A z-score becomes a judgement once you set thresholds. This module uses three bands, taken from the empirical rule.</p>
<div id="tbl-z-bands" class="tbl-grid quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-z-bands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.10: Three bands for judging a value by its z-score
</figcaption>
<div aria-describedby="tbl-z-bands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-grid caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>z-score, ignoring the sign</th>
<th>Label</th>
<th>Share expected under a normal curve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Less than 2</td>
<td>Typical</td>
<td>About 95 in 100</td>
</tr>
<tr class="even">
<td>2 up to 3</td>
<td>Unusual</td>
<td>About 4 or 5 in 100</td>
</tr>
<tr class="odd">
<td>3 or more</td>
<td>Extreme</td>
<td>About 3 in 1,000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>“Unusual” is a statement about frequency. It says a value of this size turns up in roughly one case in twenty. In a file of 200 you should expect about 9 unusual values by chance alone. An unusual value is a prompt to look again, the same prompt the <span class="math inline">\(1.5 \times IQR\)</span> fences gave you in chapter 1.</p>
<p>“Extreme” is stronger. Under a normal curve, a value three or more standard deviations from the mean turns up about 3 times in 1,000 cases. When you find one, check the record first, then the circumstances, and only then treat it as part of the ordinary spread.</p>
<section id="the-unusual-waits-in-the-teaching-dataset" class="level3">
<h3 class="anchored" data-anchor-id="the-unusual-waits-in-the-teaching-dataset">The unusual waits in the teaching dataset</h3>
<p>Seven of the 200 waiting times lie two or more standard deviations from the mean.</p>
<div id="tbl-unusual-waits" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-unusual-waits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.11: The seven waiting times two or more standard deviations from the mean
</figcaption>
<div aria-describedby="tbl-unusual-waits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<thead>
<tr class="header">
<th>Respondent</th>
<th>Wait, minutes</th>
<th><span class="math inline">\(z\)</span></th>
<th>Band</th>
<th>Beyond the IQR fences?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>85</td>
<td>90</td>
<td>3.74</td>
<td>Extreme</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>149</td>
<td>12</td>
<td>-2.81</td>
<td>Unusual</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>58</td>
<td>77</td>
<td>2.65</td>
<td>Unusual</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>189</td>
<td>14</td>
<td>-2.64</td>
<td>Unusual</td>
<td>Yes</td>
</tr>
<tr class="odd">
<td>191</td>
<td>19</td>
<td>-2.22</td>
<td>Unusual</td>
<td>No</td>
</tr>
<tr class="even">
<td>138</td>
<td>20</td>
<td>-2.14</td>
<td>Unusual</td>
<td>No</td>
</tr>
<tr class="odd">
<td>147</td>
<td>21</td>
<td>-2.05</td>
<td>Unusual</td>
<td>No</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The two rules largely agree. Every case beyond the chapter 1 fences also has a z-score beyond 2, and the z-score rule adds three short waits just inside the lower fence. The IQR rule works from quartiles and suits any shape. The z-score rule works from the mean and standard deviation and suits a distribution close to normal, which waiting time is.</p>
<p>The file contains 6 unusual values and 1 extreme one, against a normal-curve prediction of about 9 and 0.5. The counts agree closely, and the extreme case, respondent 85, needs a closer look.</p>
<div class="worked-example">
<p><span class="we-label">Worked example 2.6</span></p>
<section id="explaining-a-z-score-in-plain-language" class="level3">
<h3 class="anchored" data-anchor-id="explaining-a-z-score-in-plain-language">Explaining a z-score in plain language</h3>
<div class="we-problem">
<p>Respondent 85 waited 90 minutes. The same customer gave a satisfaction score of 4.50, above the mean of 3.81.</p>
<p>Calculate the z-score for the wait, classify it, and write two sentences for a branch manager who has never heard of a z-score. Then say what you would check before acting on it.</p>
</div>
<div class="we-solution">
<p><strong>The z-score:</strong></p>
<p><span class="math display">\[z = \frac{90 - 45.455}{11.905} = \frac{44.545}{11.905} = 3.74\]</span></p>
<p><strong>The band:</strong> <span class="math inline">\(3.74\)</span> is beyond 3, so the wait is <strong>extreme</strong>.</p>
<p><strong>For the manager:</strong></p>
<blockquote class="blockquote">
<p>One customer waited 90 minutes, nearly twice the average wait and far beyond anything else in the month. Waits this far from the average should happen fewer than 3 times in 1,000 customers, so this one needs an explanation.</p>
</blockquote>
<p>The sentences convey the meaning of the z-score without using the symbol. They state the distance, the reference point and the rarity.</p>
<p><strong>What to check first:</strong> A 90-minute wait paired with a satisfaction score of 4.50 is an odd combination, because long waits usually go with low satisfaction. Three explanations fit: the time was recorded wrongly, perhaps 9 or 19 minutes typed as 90, the customer chose to wait for a particular member of staff, or the customer was patient. The first is a data error to correct and record. The second and third are real events that belong in the file. The z-score told you where to look. The record and the circumstances tell you what you found.</p>
</div>
</section>
</div>
<div id="tryit-2-6" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.6: Classify the waits">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.6: Classify the waits
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the waiting-time mean of 45.455 minutes and standard deviation of 11.905.</p>
<ol type="1">
<li>Calculate the z-score for waits of 20, 52 and 82 minutes, to two decimal places.</li>
<li>Classify each as typical, unusual or extreme.</li>
<li>Find the waiting time that sits exactly 2 standard deviations above the mean, and the one that sits 1 standard deviation below it.</li>
<li>Write one plain-language sentence about the 82-minute wait for a manager.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>20 minutes: <span class="math inline">\(z = (20 - 45.455) \div 11.905 = -25.455 \div 11.905 = -2.14\)</span>. 52 minutes: <span class="math inline">\(z = (52 - 45.455) \div 11.905 = 6.545 \div 11.905 = 0.55\)</span>. 82 minutes: <span class="math inline">\(z = (82 - 45.455) \div 11.905 = 36.545 \div 11.905 = 3.07\)</span>.</li>
<li>20 minutes is <strong>unusual</strong>, below the mean. 52 minutes is <strong>typical</strong>. 82 minutes is <strong>extreme</strong>, just past 3.</li>
<li>Two above: <span class="math inline">\(45.455 + 2 \times 11.905 = 69.3\)</span> minutes. One below: <span class="math inline">\(45.455 - 11.905 = 33.6\)</span> minutes.</li>
<li>For example: “A customer who waits 82 minutes has waited about 37 minutes longer than average, and a wait that long should happen to fewer than 3 customers in 1,000.”</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-compare-z" class="level2">
<h2 class="anchored" data-anchor-id="sec-compare-z">Comparing values in different units</h2>
<p>A z-score has no units, so it lets you compare a customer’s wait with the same customer’s spend, or a branch’s sales with its complaints. The question it answers is: <strong>which value is further from its own average, measured in that variable’s own spread?</strong></p>
<div class="worked-example">
<p><span class="we-label">Worked example 2.7</span></p>
<section id="which-figure-is-most-out-of-line" class="level3">
<h3 class="anchored" data-anchor-id="which-figure-is-most-out-of-line">Which figure is most out of line?</h3>
<div class="we-problem">
<p>Respondent 5 waited 61 minutes, spent 161.90 USD and gave a satisfaction score of 2.77.</p>
<div id="tbl-respondent-5" class="tbl-apa quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-respondent-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.12: Respondent 5 against the means and standard deviations of three variables
</figcaption>
<div aria-describedby="tbl-respondent-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="tbl-apa caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Value</th>
<th>Mean</th>
<th>Standard deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Waiting_Time_Mins</code></td>
<td>61</td>
<td>45.455</td>
<td>11.905</td>
</tr>
<tr class="even">
<td><code>Spending</code></td>
<td>161.90</td>
<td>505.650</td>
<td>256.839</td>
</tr>
<tr class="odd">
<td><code>Satisfaction</code></td>
<td>2.77</td>
<td>3.814</td>
<td>0.740</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Standardise all three values and decide which one lies furthest from its own average.</p>
</div>
<div class="we-solution">
<p><span class="math display">\[z_{\text{wait}} = \frac{61 - 45.455}{11.905} = 1.31\]</span></p>
<p><span class="math display">\[z_{\text{spend}} = \frac{161.90 - 505.650}{256.839} = -1.34\]</span></p>
<p><span class="math display">\[z_{\text{satisfaction}} = \frac{2.77 - 3.814}{0.740} = -1.41\]</span></p>
<p>All three are typical in size, between 1.3 and 1.5 standard deviations from their means. The satisfaction score is the furthest out, by a small margin. The raw numbers hide this completely: 343.75 USD below average sounds far larger than 1.04 points below average, and in the units of each variable’s own spread they are about the same distance.</p>
<p>The pattern across the three is the useful finding. This customer waited longer than most, spent less than most and was less satisfied than most. One customer proves nothing, and a manager who found the same pattern across many customers would have a lead to follow.</p>
<p>One caution applies. <code>Spending</code> is right-skewed, so a z-score of <span class="math inline">\(-1.34\)</span> there does not indicate the same rarity as <span class="math inline">\(-1.34\)</span> on a normal curve. The comparison of distances remains valid. The empirical-rule shares apply only to the two variables close to normal.</p>
</div>
</section>
</div>
<div id="tryit-2-7" class="callout callout-style-default callout-tip callout-titled" title="Try It 2.7: Compare across units">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Try It 2.7: Compare across units
</div>
</div>
<div class="callout-body-container callout-body">
<p>A student scores 68 in a statistics test where the class mean is 60 and the standard deviation is 5. The same student scores 75 in a marketing test where the class mean is 70 and the standard deviation is 10.</p>
<ol type="1">
<li>Calculate both z-scores.</li>
<li>In which test did the student perform better relative to the class?</li>
<li>What statistics mark would match the student’s relative position in marketing?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Check your answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Check your answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Statistics: <span class="math inline">\(z = (68 - 60) \div 5 = 8 \div 5 = 1.6\)</span>. Marketing: <span class="math inline">\(z = (75 - 70) \div 10 = 5 \div 10 = 0.5\)</span>.</li>
<li><strong>Statistics:</strong> The student ranks 1.6 standard deviations above the class there, against 0.5 in marketing, even though the raw marketing mark is higher.</li>
<li>Convert <span class="math inline">\(z = 0.5\)</span> back using the statistics mean and standard deviation: $x = 60 + 0.5 = $ <strong>62.5</strong>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="section-summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="section-summary">Section summary</h2>
<p>The normal distribution is a symmetric bell-shaped model fixed by its mean and standard deviation, and the area under it is the share of cases. The empirical rule puts about 68, 95 and 99.7 per cent of cases within one, two and three standard deviations, and waiting time in the teaching dataset follows it closely. Chebyshev’s rule gives a floor that applies to any shape. A z-score measures distance from the mean in standard deviations, and it converts back with <span class="math inline">\(x = \bar{x} + z s\)</span>. Values beyond 2 are unusual and values beyond 3 are extreme, and both are prompts to check the record.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Next:</strong> <a href="week02-part3.html">Part 3, areas, percentiles and normality</a> covers the standard normal table, percentiles from the normal model, and how to check whether a variable is close enough to normal.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/mohammedalisharafuddin\.github\.io\/dmm-textbook");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../weeks/week02.html" class="pagination-link" aria-label="Part 1: The shape of a distribution">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Part 1: The shape of a distribution</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../weeks/week02-part3.html" class="pagination-link" aria-label="Part 3: Areas, percentiles and checking normality">
        <span class="nav-page-text"><span class="chapter-title">Part 3: Areas, percentiles and checking normality</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>
